# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastMode <- function(x, narm = FALSE) {
    .Call(`_jaid_fastMode`, x, narm)
}

fastModeX <- function(x, narm = FALSE) {
    .Call(`_jaid_fastModeX`, x, narm)
}

